export const APPOINTMENT_SAVE_DATE = "APPOINTMENT_SAVE_DATE";
export const APPOINTMENT_SAVE_ADDRESS = "APPOINTMENT_SAVE_ADDRESS";
export const APPOINTMENT_SAVE_PAYMENT_METHOD =
  "APPOINTMENT_SAVE_PAYMENT_METHOD";

export const APPOINTMENT_CREATE_REQUEST = "APPOINTMENT_CREATE_REQUEST";
export const APPOINTMENT_CREATE_SUCCESS = "APPOINTMENT_CREATE_SUCCESS";
export const APPOINTMENT_CREATE_FAIL = "APPOINTMENT_CREATE_FAIL";

export const APPOINTMENT_DETAILS_REQUEST = "APPOINTMENT_DETAILS_REQUEST";
export const APPOINTMENT_DETAILS_SUCCESS = "APPOINTMENT_DETAILS_SUCCESS";
export const APPOINTMENT_DETAILS_FAIL = "APPOINTMENT_DETAILS_FAIL";

export const APPOINTMENT_PAY_REQUEST = "APPOINTMENT_PAY_REQUEST";
export const APPOINTMENT_PAY_SUCCESS = "APPOINTMENT_PAY_SUCCESS";
export const APPOINTMENT_PAY_FAIL = "APPOINTMENT_PAY_FAIL";
export const APPOINTMENT_PAY_RESET = "APPOINTMENT_PAY_RESET";
